app/booking/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired


class BookingDateForm(FlaskForm):
    date = DateField('Date', validators=[DataRequired()], format='%Y-%m-%d')
    submit = SubmitField('Pick date')

app/booking/__init__.py
from flask import Blueprint

bp = Blueprint('booking', __name__)

from app.booking import routes

app/booking/routes.py
from app import db
from app.booking import bp
from flask import render_template, flash, redirect, url_for, request, jsonify
from flask_login import login_required, current_user
from app.booking.forms import BookingDateForm
from app.models import MapPoint, Place, Booking
from sqlalchemy import distinct
from datetime import date, datetime


@bp.route('/index', methods=['GET', 'POST'])
@bp.route('/index/<book_date>', methods=['GET', 'POST'])
def index(book_date=None):
    form = BookingDateForm()
    rows = [row[0] for row in db.session.query(distinct(MapPoint.y_coordinate)).all()]
    points = {row: MapPoint.query.filter_by(y_coordinate=row).all() for row in rows}
    if request.method == 'GET' and book_date:
        form.date.data = book_date
    if request.method == 'GET' and not book_date:
        form.date.data = date.today()
    if form.validate_on_submit():
        return redirect(url_for('booking.index', book_date=form.date.data))
    return render_template('booking/index.html', points=points, form=form)


@bp.route('/book/<place>/<book_date>')
@login_required
def book(book_date, place):
    place = Place.query.filter_by(id=place).first_or_404()
    if place.is_booked_on_date(book_date):
        flash('This place is booked on chosen date. Please choose another one.')
        return redirect(url_for('booking.index', book_date=book_date))
    booking = Booking(place_id=place.id,
                      user_id=current_user.id,
                      booking_date=datetime.strptime(book_date, '%Y-%m-%d').date())
    db.session.add(booking)
    db.session.commit()
    return render_template('booking/book.html', booking=booking)


@bp.route('/cancel_booking', methods=['POST'])
@login_required
def cancel_booking():
    return jsonify({'text': Booking.cancel(request.form['id']),
                    'booking_status': Booking.query.get(int(request.form['id'])).get_status()})

app/templates/booking/book.html
{% extends "base.html" %}

{% block content %}
<p>
    Booking of spot {{booking.place_id}} on {{booking.booking_date}} is successful.<br>
    You can view and manage your bookings at <a href="{{url_for('user.user',id=current_user.id)}}">Profile Page</a>.
</p>
{% endblock %}

app/templates/booking/index.html
{% extends "base.html" %}

{% block content %}
{% if current_user.is_authenticated %}
<p>Select workspace at Geeky Galaxy Center Inc.</p>
<form action="" method="post">
                    {{ form.hidden_tag() }}
                    <p>{{ form.date.label }}<br>
                        <input type="date" name="date" />
                        {% for error in form.date.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>{{ form.submit() }}</p>
</form>
{%else %}
<p>Welcome to Blazing Booking - online service which helps you
    to find and book workspace at Geeky Galaxy Center Inc.</p>
{% endif %}
<div class="place map">
    {% if points %}
    <table>
        {% for key, row in points.items() %}
        <tr>
            {% for point in row %}
            <td>
                {% if point.place_id %}
                <img src="/static/table.png" alt="table" height="100" width="100">
                {% if current_user.is_authenticated %}
                    <!-- TODO: optimize this query -->
                    {% if point.place.is_booked_on_date(form.date.data) %}
                    <div><p>This place is booked</p></div>
                    {% else %}
                    <div><a href="{{url_for('booking.book',place=point.place_id, book_date=form.date.data)}}">Book</a></div>
                    {% endif %}
                {% endif %}
                {% else %}
                <img src="/static/hall.png" alt="hall" height="100" width="100">
                {% endif %}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</div>
{%if current_user.is_anonymous %}
<div>
    <p>
    <a href="{{ url_for('auth.login') }}">Sign In</a>
     to book your favourite spot at Geeky Galaxy Center Inc.
    </p>
</div>
{% endif%}
{% endblock %}