app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


class EditProfileForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    bio = TextAreaField('About me', validators=[Length(min=0, max=300)])
    submit = SubmitField('Save')

app/user/__init__.py
from flask import Blueprint

bp = Blueprint('user', __name__)

from app.user import routes

app/user/routes.py
from app import db
from app.user import bp
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_required, current_user
from app.user.forms import EditProfileForm
from app.auth.forms import ChangePasswordForm
from app.models import User


@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    profile_form = EditProfileForm()
    password_form = ChangePasswordForm()
    if profile_form.validate_on_submit():
        current_user.name = profile_form.name.data
        current_user.bio = profile_form.bio.data
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('user.edit_profile'))
    elif request.method == 'GET':
        profile_form.name.data = current_user.name
        profile_form.bio.data = current_user.bio
    elif password_form.validate_on_submit():
        # user = User.query.filter_by(email=current_user.email).first()
        if not current_user.check_password(password_form.old_password.data):
            flash('Old password is incorrect.')
            return redirect(url_for('user.edit_profile'))
        current_user.set_password(password_form.new_password.data)
        db.session.commit()
        flash('Your password successfully changed.')
        return redirect(url_for('user.edit_profile'))
    return render_template('user/edit_profile.html',
                           title='Edit Profile',
                           profile_form=profile_form,
                           password_form=password_form,
                           user=current_user)


@bp.route('/user/<id>')
@login_required
def user(id):
    user = User.query.filter_by(id=id).first_or_404()
    return render_template('user/user.html', user=user)

app/templates/base.html
<html>
    <head>
        {% if title %}
        <title>{{ title }} - Blazing Booking</title>
        {% else %}
        <title>Welcome to Blazing Booking</title>
        {% endif %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block css %}
        {% endblock %}
        {% block scripts %}
        {% endblock %}
    </head>
    <body>
        <div><a href="{{ url_for('booking.index') }}">Home</a></div>
        {% if current_user.is_anonymous %}
        <div><a href="{{ url_for('auth.register') }}">Register</a></div>
        <div><a href="{{ url_for('auth.login') }}">Login</a></div>
        {% else %}
        <div><a href="{{ url_for('user.user', id=current_user.id) }}">Profile</a></div>
        <div><a href="{{ url_for('auth.logout') }}">Logout</a></div>
        {% endif %}
        <hr>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
        {% block footer %}
        <div>
            <p>
                © 2019 All rights reserved.
            </p>
        </div>
        {% endblock %}
    </body>
</html>

app/templates/book.html
{% extends "base.html" %}

{% block content %}
<p>
    Booking of spot {{booking.place_id}} on {{booking.booking_date}} is successful.<br>
    You can view and manage your bookings at <a href="{{url_for('user',id=current_user.id)}}">Profile Page</a>.
</p>
{% endblock %}

app/templates/edit_profile.html
{% extends "base.html" %}

{% block content %}
<h1>Profile Page</h1>
<table>
        <tr valign="top">
            <td>
                <img src="{{ user.avatar(128) }}">
                <div><a href="{{ url_for('user', id=current_user.id) }}">Back</a></div>
            </td>
            <td>
                <div>tabs scripts here</div>
                <form action="" method="post">
                    {{ profile_form.hidden_tag() }}
                    <p>
                        {{ profile_form.name.label }}<br>
                        {{ profile_form.name(size=32) }}<br>
                        {% for error in profile_form.name.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{ profile_form.bio.label }}<br>
                        {{ profile_form.bio(cols=50, rows=6) }}<br>
                        {% for error in profile_form.bio.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>{{ profile_form.submit() }}</p>
                </form>
                <form action="" method="post">
                    {{ password_form.hidden_tag() }}
                    <p>
                        {{ password_form.old_password.label }}<br>
                        {{ password_form.old_password(size=32) }}<br>
                        {% for error in password_form.old_password.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{ password_form.new_password.label }}<br>
                        {{ password_form.new_password(size=32) }}<br>
                        {% for error in password_form.new_password.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{ password_form.new_password2.label }}<br>
                        {{ password_form.new_password2(size=32) }}<br>
                        {% for error in password_form.new_password2.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>{{ password_form.submit() }}</p>
                </form>
            </td>
        </tr>
    </table>
{% endblock %}

app/templates/email_confirm.html
{% extends "base.html" %}

{% block content %}
<p>
    Almost there!<br>
    Follow the link in the email we've just sent you to confirm the registration.
</p>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<p>Welcome to Blazing Booking - online service which helps you
    to find and book workspace at Geeky Galaxy Center Inc.</p>
<form action="" method="post">
                    {{ form.hidden_tag() }}
                    <p>{{ form.date.label }}<br>
                        <input type="date" name="date" />
                        {% for error in form.date.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>{{ form.submit() }}</p>
</form>

<div class="place map">
    {% if points %}
    <table>
        {% for key, row in points.items() %}
        <tr>
            {% for point in row %}
            <td>
                {% if point.place_id %}
                <img src="/static/table.png" alt="table" height="100" width="100">
                <!-- TODO: optimize this query -->
                {% if point.place.is_booked_on_date(form.date.data) %}
                <div><p>This place is booked</p></div>
                {% else %}
                <div><a href="{{url_for('book',place=point.place_id, book_date=form.date.data)}}">Book</a></div>
                {% endif %}
                {% else %}
                <img src="/static/hall.png" alt="hall" height="100" width="100">
                {% endif %}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</div>
{%if not current_user.is_authenticated %}
<div>
    <p>
    <a href="{{ url_for('login') }}">Sign In</a>
     to book your favourite spot at Geeky Galaxy Center Inc.
    </p>
</div>
{% endif%}
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
    <h1>Login</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
    <p>
        <a href="{{ url_for('register') }}">Register</a>
    </p>
    <p>
        <a href="{{ url_for('reset_password_request') }}">Forgot Password?</a>
    </p>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
{% endblock %}

{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script>
        function cancel_booking(sourceElem,newStatusElem, destElem) {
            $(destElem).html('<img src="{{ url_for('static', filename='loading.gif') }}">');
            $.post('/cancel_booking', {
                id: $(sourceElem).text()
            }).done(function(response) {
                $(destElem).html(response["text"]);
                $(newStatusElem).html(response["booking_status"]);
            }).fail(function() {
                $(destElem).text("Error occured while communicating server.");
            });
        }
</script>
{% endblock %}


{% block content %}
<h1>Profile Page</h1>
<table>
        <tr valign="top">
            <td>
                <img src="{{ user.avatar(128) }}">
                {% if user == current_user %}
                <div><a href="{{ url_for('edit_profile') }}">Edit</a></div>
                {% endif %}
            </td>
            <td>
                <div class="container">
                  <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#overview">Overview</a></li>
                    <li><a data-toggle="tab" href="#bookings">My Bookings</a></li>
                    <li><a data-toggle="tab" href="#settings">Settings</a></li>
                  </ul>
                    <div class="tab-content">
                        <div id="overview" class="tab-pane fade in active">
                            <h3>Hi, {{ user.name }}</h3>
                            {% if user.bio %}
                            <p>{{ user.bio }}</p>
                            {% endif %}
                        </div>
                        <div id="bookings" class="tab-pane fade">
                            <h3>Here you can check your booking information.</h3>
                            {% if user.get_user_bookings() %}
                            <table>
                                <tr>
                                    <th>
                                        <p>Place</p>
                                    </th>
                                    <th>
                                        <p>Booking date</p>
                                    </th>
                                    <th>
                                        <p>Status</p>
                                    </th>
                                    <th>
                                        <p>Price</p>
                                    </th>
                                </tr>
                                {% for booking in user.get_user_bookings() %}
                                <tr>
                                    <td>
                                        <p>{{booking.place_id}}</p>
                                    </td>
                                    <td>
                                        <p>{{booking.booking_date}}</p>
                                    </td>
                                    <td>
                                        <p id="booking_status{{booking.id}}">{{booking.get_status()}}</p>
                                    </td>
                                    <td>
                                        <p>{{booking.get_place_price()}}</p>
                                    </td>
                                    {%if booking.is_new_booking() %}
                                    <td>
                                        <p>
                                            <span id="booking{{ booking.id }}" hidden>{{ booking.id }}</span>
                                            <span id="cancel{{ booking.id }}">
                                                <a href="javascript:cancel_booking('#booking{{booking.id}}',
                                                '#booking_status{{booking.id}}',
                                                '#cancel{{booking.id}}');">Cancel</a>
                                            </span>
                                        </p>
                                    </td>
                                    {% endif %}
                                </tr>
                                {% endfor %}
                            </table>
                            {% else %}
                            <p>
                                You have not booked yet.
                            </p>
                            {% endif %}
                        </div>
                        <div id="settings" class="tab-pane fade">
                            <p>Enable integration with Google Calendar</p>
                            <br>
                            <h4>Email notification</h4>
                            <p>Notifications about bookings</p>
                            <p>Random news</p>
                        </div>
                      </div>
                </div>
            </td>
        </tr>
    </table>
{% endblock %}